name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-macos:
    name: Build macOS DMG
    runs-on: macos-15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Install Electron app dependencies
        run: npx electron-builder install-app-deps

      - name: Build React app
        run: npm run dist-mac

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: release-builds/

  # build-windows:
  #   name: Build Windows installer
  #   runs-on: windows-latest

  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Install Electron app dependencies
  #       run: npx electron-builder install-app-deps

  #     - name: Build React app
  #       run: npm run build

  #     - name: Build Windows NSIS installer
  #       run: npx electron-builder --win --publish=never

  #     - name: Upload Windows artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: windows-artifacts
  #         path: release-builds/

  # build-linux:
  #   name: Build Linux AppImage
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Install Electron app dependencies
  #       run: npx electron-builder install-app-deps

  #     - name: Build React app
  #       run: npm run build

  #     - name: Build Linux AppImage
  #       run: npx electron-builder --linux --publish=never

  #     - name: Upload Linux artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: linux-artifacts
  #         path: release-builds/
